version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "fb:b5:2b:bb:fe:84:5e:fd:2b:bc:ea:a5:84:46:21:ea"
      - run: git config --global user.email "jacktan165@gmail.com"
      - run: git config --global user.name "Jack Tan"
      - run: yarn release
      - run: git push
workflows:
  version: 2
  verify:
    jobs:
      - build
      - release:
          requires:
            - build
