import { PortfolioOwnProps, PortfolioImageResponse } from "../Portfolio.types";

export const mockPortfolioImageProps: PortfolioImageResponse[] = [
  {
    id: 1,
    category: {
      type: "architecture",
    },
    mainPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    categoryPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    image: {
      id: "1",
      url: "/facebook.jpg",
      name: "architecture image",
      width: 250,
      height: 250,
    },
    title: "architecture title",
    description: "architecture description",
    modalImages: [
      {
        id: 1,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
      {
        id: 2,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
      {
        id: 3,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
      {
        id: 4,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
      {
        id: 5,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
      {
        id: 6,
        image: {
          url: "/facebook.jpg",
          name: "architecture alt text",
          width: 250,
          height: 250,
        },
        caption: "architecture caption",
      },
    ],
  },
  {
    id: 1,
    category: {
      type: "photography",
    },
    mainPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    categoryPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    image: {
      id: "1",
      url: "/twitter.jpg",
      name: "photography image",
      width: 250,
      height: 250,
    },
    title: "photography title",
    description: "photography description",
    modalImages: [
      {
        id: 1,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
      {
        id: 2,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
      {
        id: 3,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
      {
        id: 4,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
      {
        id: 5,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
      {
        id: 6,
        image: {
          url: "/twitter.jpg",
          name: "photography alt text",
          width: 250,
          height: 250,
        },
        caption: "photography caption",
      },
    ],
  },
  {
    id: 1,
    category: {
      type: "illustration",
    },
    mainPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    categoryPositions: {
      mobileColumnStartPosition: 3,
      mobileColumnEndPosition: 5,
      tabletColumnStartPosition: 5,
      tabletColumnEndPosition: 7,
      desktopColumnStartPosition: 6,
      desktopColumnEndPosition: 8,
      mobileRowStartPosition: 4,
      mobileRowEndPosition: 6,
      tabletRowStartPosition: 6,
      tabletRowEndPosition: 8,
      desktopRowStartPosition: 6,
      desktopRowEndPosition: 8,
    },
    image: {
      id: "1",
      url: "/instagram.jpg",
      name: "illustration image",
      width: 250,
      height: 250,
    },
    title: "illustration title",
    description: "illustration description",
    modalImages: [
      {
        id: 1,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
      {
        id: 2,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
      {
        id: 3,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
      {
        id: 4,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
      {
        id: 5,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
      {
        id: 6,
        image: {
          url: "/instagram.jpg",
          name: "illustration alt text",
          width: 250,
          height: 250,
        },
        caption: "illustration caption",
      },
    ],
  },
];

export const mockPortfolioCmsResponse: PortfolioOwnProps = {
  loaderText: "Youngi Kim",
  portfolioImagesResponse: [...mockPortfolioImageProps],
};
